ruby_version: ruby-1.9.3-p194        
bundler_version: 1.7.12
hooks:                                  
  worker_setup: bundle exec rake db:migrate # Runs once for each worker to do, e.g., database setup
test_pattern:                                
  - spec/**/*_spec.rb                       
tests:
  - bundle exec rspec
